# Generated by Django 5.0.7 on 2024-10-19 15:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_drink', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('energy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clothing', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entertainment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
